DROP TABLE QUOTEEJB cascade constraints;

CREATE TABLE QUOTEEJB
  (LOW DECIMAL(14, 2) NULL,
   OPEN1 DECIMAL(14, 2) NULL,
   VOLUME NUMBER NOT NULL,
   PRICE DECIMAL(14, 2) NULL,
   HIGH DECIMAL(14, 2) NULL,
   COMPANYNAME VARCHAR2(250) NULL,
   SYMBOL VARCHAR2(250) NOT NULL,
   CHANGE1 NUMBER NOT NULL);

ALTER TABLE QUOTEEJB
  ADD CONSTRAINT PK_QUOTEEJB PRIMARY KEY (SYMBOL);

