trigger: none

variables:
- group: Repo_Env

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '3d034576-aa51-4760-88fd-3fe8617a5399'
    definition: '9'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Pipeline.Workspace)/10_JAVA'
    Contents: '**'
    TargetFolder: '$(system.defaultworkingdirectory)'

- task: Docker@2
  displayName: 'daytrader-accounts'
  inputs:
    containerRegistry: 'ACR'
    repository: 'daytrader-accounts'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-accountsrepo/daytrader-accountsapp/daytrader-accounts/Dockerfile'
    tags: '15'

- task: Docker@2
  displayName: 'daytrader-gateway'
  inputs:
    containerRegistry: 'ACR'
    repository: 'daytrader-gateway'
    tags: '15'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-gatewayrepo/daytrader-gatewayapp/daytrader-gateway/Dockerfile'


- task: Docker@2
  displayName: 'daytrader-portfolios'
  inputs:
    containerRegistry: 'ACR'
    repository: 'daytrader-portfolios'
    tags: '15'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-portfoliosrepo/daytrader-portfoliosapp/daytrader-portfolios/Dockerfile'

- task: Docker@2
  displayName: 'daytrader-quotes'
  inputs:
    containerRegistry: 'ACR'
    repository: 'daytrader-quotes'
    tags: '15'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-quotesrepo/daytrader-quotesapp/daytrader-quotes/Dockerfile'

- task: Docker@2
  displayName: 'daytrader-web'
  inputs:
    containerRegistry: 'ACR'
    repository: 'daytrader-web'
    tags: '15'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-webrepo/daytrader-webapp/daytrader-web/Dockerfile'

- script: |
    echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
    az devops configure --defaults organization=https://dev.azure.com/{OrganizationName} project="GXEnablement" --use-git-aliases true
    if [[ $(Repo_ID) == 1 ]]
    then
      az pipelines run --branch master --name "30.1 Docker compose with Postman" -p GXEnablement
    elif [[ $(Repo_ID) == 2 ]]
    then
      az pipelines run --branch master --name "30.2 Docker compose with Postman" -p GXEnablement
    fi
  env:
    AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
  displayName: 'Triggering next pipeline'