mkdir all_combined
cp "pods/accounts/deployment.yaml"                        "all_combined/accounts_deployment.yaml"
cp "pods/accounts/service.yaml"                           "all_combined/accounts_service.yaml"
cp "pods/gateway/deployment.yaml"                         "all_combined/gateway_deployment.yaml"
cp "pods/gateway/service.yaml"                            "all_combined/gateway_service.yaml"
cp "pods/portfolios/deployment.yaml"                      "all_combined/portfolios_deployment.yaml"
cp "pods/portfolios/service.yaml"                         "all_combined/portfolios_service.yaml"
cp "pods/quotes/deployment.yaml"                          "all_combined/quotes_deployment.yaml"
cp "pods/quotes/service.yaml"                             "all_combined/quotes_service.yaml"
cp "pods/report-generator/deployment.yaml"                "all_combined/report-generator_deployment.yaml"
cp "pods/scdf-trade-generator/deployment.yaml"            "all_combined/scdf-trade-generator_deployment.yaml"
cp "pods/scdf-trade-generator/service.yaml"               "all_combined/scdf-trade-generator_service.yaml"
cp "pods/scdf-trade-processor/deployment.yaml"            "all_combined/scdf-trade-processor_deployment.yaml"
cp "pods/scdf-trade-processor/service.yaml"               "all_combined/scdf-trade-processor_service.yaml"
cp "pods/scdf-trade-validation/deployment.yaml"           "all_combined/scdf-trade-validation_deployment.yaml"
cp "pods/scdf-trade-validation/service.yaml"              "all_combined/scdf-trade-validation_service.yaml"
cp "pods/trade-consumer/deployment.yaml"                  "all_combined/trade-consumer_deployment.yaml"
cp "pods/trade-consumer/service.yaml"                     "all_combined/trade-consumer_service.yaml"
cp "pods/trade-producer/deployment.yaml"                  "all_combined/trade-producer_deployment.yaml"
cp "pods/trade-producer/service.yaml"                     "all_combined/trade-producer_service.yaml"
cp "pods/web/deployment.yaml"                             "all_combined/web_deployment.yaml"
cp "pods/web/service.yaml"                                "all_combined/web_service.yaml"
cp "pods/web-react-npm/deployment.yaml"                   "all_combined/web-react-npm_deployment.yaml"
cp "pods/web-react-npm/service.yaml"                      "all_combined/web-react-npm_service.yaml"
cp "pods/web-react-static/deployment.yaml"                "all_combined/web-react-static_deployment.yaml"
cp "pods/web-react-static/service.yaml"                   "all_combined/web-react-static_service.yaml"
cp "pods/web-mfe-accounts-npm/deployment.yaml"            "all_combined/web-mfe-accounts-npm_deployment.yaml"
cp "pods/web-mfe-accounts-npm/service.yaml"               "all_combined/web-mfe-accounts-npm_service.yaml"
cp "pods/web-mfe-container-npm/deployment.yaml"           "all_combined/web-mfe-container-npm_deployment.yaml"
cp "pods/web-mfe-container-npm/service.yaml"              "all_combined/web-mfe-container-npm_service.yaml"
cp "pods/web-mfe-portfolios-npm/deployment.yaml"          "all_combined/web-mfe-portfolios-npm_deployment.yaml"
cp "pods/web-mfe-portfolios-npm/service.yaml"             "all_combined/web-mfe-portfolios-npm_service.yaml"
cp "pods/web-mfe-quotes-npm/deployment.yaml"              "all_combined/web-mfe-quotes-npm_deployment.yaml"
cp "pods/web-mfe-quotes-npm/service.yaml"                 "all_combined/web-mfe-quotes-npm_service.yaml"


cp "configmaps-mysql/config-map-accounts-db-mysql.yaml"   "all_combined/config-map-accounts-db-mysql.yaml"
cp "configmaps-mysql/config-map-portfolios-db-mysql.yaml" "all_combined/config-map-portfolios-db-mysql.yaml"
cp "configmaps-mysql/config-map-quotes-db-mysql.yaml"     "all_combined/config-map-quotes-db-mysql.yaml"
cp "configmaps-mysql/config-map-service-urls.yaml"        "all_combined/config-map-service-urls.yaml"

